config/routes.rb
Rails.application.routes.draw do
  root to: "posts#landing"

  resources :posts do
    resources :responses
  end

  devise_for :users do
    resources :trips
  end


  resources :trips
  resources :responses

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :responses
end

app/models/response.rb
class Response < ApplicationRecord
  belongs_to :post
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user
  geocoded_by :address
  after_validation :geocode
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :trips
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  def landing
    if current_user
      @trips = current_user.trips
      @hash = Gmaps4rails.build_markers(@trips) do |trip, marker|
        marker.lat trip.latitude
        marker.lng trip.longitude
        marker.infowindow (trip.address + '<br>' + trip.trip_date.to_s + '<br>' + trip.description)
      end
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:name, :title, :content)
    end
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  before_action :set_response, only: [:show, :edit, :update, :destroy]

  # GET /responses
  # GET /responses.json
  def index
    @responses = Response.all
  end

  # GET /responses/1
  # GET /responses/1.json
  def show
  end

  # GET /responses/new
  def new
    @response = Response.new
  end

  # GET /responses/1/edit
  def edit
  end

  # POST /responses
  # POST /responses.json
  def create
    @post = Post.find(params[:post_id])
    @response = @post.responses.create!(response_params)
    redirect_to post_path(@post)
  end

  # PATCH/PUT /responses/1
  # PATCH/PUT /responses/1.json
  def update
    respond_to do |format|
      if @response.update(response_params)
        format.html { redirect_to @response, notice: 'Response was successfully updated.' }
        format.json { render :show, status: :ok, location: @response }
      else
        format.html { render :edit }
        format.json { render json: @response.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /responses/1
  # DELETE /responses/1.json
  def destroy
    @response.destroy
    @post = Post.find(params[:post_id])
    respond_to do |format|
      format.html { redirect_to post_path(@post), notice: 'Response was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_response
      @response = Response.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def response_params
      params.require(:response).permit(:name, :content, :post_id)
    end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :destroy]

  # GET /trips
  # GET /trips.json
  def index
    @trips = Trip.all
  end

  # GET /trips/1
  # GET /trips/1.json
  def show
  end

  # GET /trips/new
  def new
    @trip = Trip.new
    @user = current_user
  end

  # GET /trips/1/edit
  def edit
    @user = current_user
  end

  # POST /trips
  # POST /trips.json
  def create
    @trip = Trip.new(trip_params)


    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, notice: 'Trip was successfully created.' }
        format.json { render :show, status: :created, location: @trip }
      else
        format.html { render :new }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trips/1
  # PATCH/PUT /trips/1.json
  def update
    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { render :show, status: :ok, location: @trip }
      else
        format.html { render :edit }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    @trip.destroy
    respond_to do |format|
      format.html { redirect_to trips_url, notice: 'Trip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip
      @trip = Trip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trip_params
      params.require(:trip).permit(:latitude, :longitude, :address, :description, :trip_date, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NwAnglers</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Cabin+Sketch:700|Squada+One" rel="stylesheet">


  <body>

    <nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">NW Anglers</a>
    </div>
    <ul class="nav navbar-nav">
      <li><%= link_to "Trip Mapper", root_path, data: { turbolinks: false }  %></li>
      <li><a href="/posts">Forum</a></li>
      <% if current_user && current_user.admin == true %>
        <h5>Currently logged in as admin</h5>
      <% end %>
    </ul>
    <ul class="nav navbar-right row">
      <% if current_user %>
      <li>Signed in: <%= current_user.email %></li>
      <li><%= link_to "Sign out", destroy_user_session_path, :method => "delete" %></li>
     <% else %>
       <li class="col-sm-6"><%= link_to "New Account", new_user_registration_path %></li>
       <li class="col-sm-6"><%= link_to "Log In", user_session_path %></li>
     <% end %>
    </ul>
  </div>
</nav>
<div class="jumbotron">
  <h1>NW Anglers</h1>
</div>
<br>

<%= flash[:alert] %>
<%= flash[:notice] %>

<div class="container">
<%= yield %>


</div>


  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_response_form.html.erb
<h2>Add a comment:</h2>
<%= form_for([@post, @post.responses.new]) do |f| %>
<div class="field">
  <%= f.label :name %><br />
  <%= f.text_field :name %>
</div>
<div class="field">
  <%= f.label :content %><br />
  <%= f.text_area :content %>
</div>


<div class="actions">
  <%= f.submit "Respond" %>
</div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Forum</h1>
  <% if current_user %>
  <%= link_to 'New Post', new_post_path %>
  <% end %>
  <br>
  <hr>



      <% @posts.each do |post| %>
      <table style="width:75%">
        <col width="500">
        <col width="300">
        <tr>
          <td><%= link_to post.title, post %></td>
          <td><%= link_to post.created_at.strftime("%b. %d  %Y"), post %></td>
        </tr>
      </table>
      <br>
      <% end %>

  <br>
</div>

app/views/posts/landing.html.erb
<script src="//maps.google.com/maps/api/js?key=AIzaSyCgXlp04HJJ5WVg5-o4izjKXRmRyfFg0pU"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->

<% if current_user %>
<h3><ins><%= link_to "View all Fishing Trips", trips_path %></ins></h3>
<p class="btn"><%= link_to "Add A Trip", new_trip_path %></p>
<br>

  <div class="row">
      <div class="col-sm-2">
        <% if current_user.trips.any? %>
        <h3>Trip Info</h3>
          <% current_user.trips.each do |trip| %>
            <li><%= link_to trip.address, trip %></li>
          <% end %>
        <% else %>
          <br>
          <p> You have not yet logged any trips. Please add a trip to place on your trip map.</p>
        <% end %>
      </div>

      <div class="col-sm-6 map container">

        <div class="innermap">

            <div id="map" style='width: 900px; height: 700px;'></div>


          <script type"text/javascript">
          mapStyle = [
            {
                "featureType": "administrative",
                "elementType": "labels.text.fill",
                "stylers": [
                    {
                        "color": "#444444"
                    }
                ]
            },
            {
                "featureType": "landscape",
                "elementType": "all",
                "stylers": [
                    {
                        "color": "#f2f2f2"
                    }
                ]
            },
            {
                "featureType": "landscape.natural.terrain",
                "elementType": "geometry.fill",
                "stylers": [
                    {
                        "visibility": "on"
                    },
                    {
                        "color": "#e5c772"
                    },
                    {
                        "weight": "0.78"
                    },
                    {
                        "saturation": "-49"
                    },
                    {
                        "lightness": "72"
                    }
                ]
            },
            {
                "featureType": "landscape.natural.terrain",
                "elementType": "geometry.stroke",
                "stylers": [
                    {
                        "color": "#d81e1e"
                    },
                    {
                        "visibility": "off"
                    }
                ]
            },
            {
                "featureType": "poi",
                "elementType": "all",
                "stylers": [
                    {
                        "visibility": "off"
                    }
                ]
            },
            {
                "featureType": "poi.park",
                "elementType": "geometry.fill",
                "stylers": [
                    {
                        "color": "#18e216"
                    },
                    {
                        "visibility": "on"
                    },
                    {
                        "lightness": "24"
                    },
                    {
                        "saturation": "-75"
                    },
                    {
                        "weight": "0.92"
                    },
                    {
                        "gamma": "2.16"
                    }
                ]
            },
            {
                "featureType": "road",
                "elementType": "all",
                "stylers": [
                    {
                        "saturation": -100
                    },
                    {
                        "lightness": 45
                    }
                ]
            },
            {
                "featureType": "road.highway",
                "elementType": "all",
                "stylers": [
                    {
                        "visibility": "simplified"
                    }
                ]
            },
            {
                "featureType": "road.arterial",
                "elementType": "labels.icon",
                "stylers": [
                    {
                        "visibility": "off"
                    }
                ]
            },
            {
                "featureType": "transit",
                "elementType": "all",
                "stylers": [
                    {
                        "visibility": "off"
                    }
                ]
            },
            {
                "featureType": "water",
                "elementType": "all",
                "stylers": [
                    {
                        "color": "#46bcec"
                    },
                    {
                        "visibility": "on"
                    }
                ]
            },
            {
                "featureType": "water",
                "elementType": "geometry.fill",
                "stylers": [
                    {
                        "visibility": "on"
                    },
                    {
                        "color": "#3d7da6"
                    },
                    {
                        "saturation": "69"
                    },
                    {
                        "lightness": "42"
                    },
                    {
                        "weight": "0.36"
                    },
                    {
                        "gamma": "1.01"
                    }
                ]
            }
        ];
          handler = Gmaps.build('Google');
          handler.buildMap({ provider: {
              center:    new google.maps.LatLng(45.5231, -122.6765),
              styles:    mapStyle
            },
            internal: {id: 'map'}
          },
          function(){
            markers = handler.addMarkers(<%= raw @hash.to_json %>);
            handler.bounds.extendWith(markers);
            handler.fitMapToBounds();
          });
          </script>
        </div>
      </div>
  </div>

<% else %>
<div class="">
  <h3>Welcome to NW Anglers</h3>
  <p>Here you can manage and store information about your fishing or scouting trips. With our trip mapping tool, you can easily store location, date, and other detailed information about every adventure out.</p>
  <p>Sign up is easy!</p>
  <p>Please log in or create an account to access the Trip Mapper and start documenting your trips.</p>
</div>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">

  <div class="container post">
    <strong>Posted by:</strong>
    <h3><%= @post.name %></h3>
    <br>
  </div>


  <div class="title container post">
    Title:
    <strong><%= @post.title %></strong>
    <div class="container post">
      <p>
        <%= @post.content %>
      </p>
    </div>
  </div>




  <hr>


  <ul>
    <% @post.responses.each do |response|%>
      <% if response.id %>
      <li>
        "<%= response.name %>" -
        <%= response.content %>
        <% if current_user && current_user.admin %>
          <%= link_to "Delete response", post_response_path(@post, response), method: "delete" %>
        <% end %>
      </li>
      <hr>
      <% end%>
    <% end %>
  </ul>
  <%= render 'response_form', post: @post %>

  <% if current_user && current_user.admin %>
    <%= link_to 'Edit', edit_post_path(@post) %> |
  <% end %>
  <%= link_to 'Back', posts_path %>
</div>

app/views/responses/_form.html.erb
<%= form_for(response) do |f| %>
  <% if response.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(response.errors.count, "error") %> prohibited this response from being saved:</h2>

      <ul>
      <% response.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="field">
    <%= f.label :post_id %>
    <%= f.number_field :post_id, default: @post.id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/responses/edit.html.erb
<h1>Editing Response</h1>

<%= render 'form', response: @response %>

<%= link_to 'Show', @response %> |
<%= link_to 'Back', responses_path %>

app/views/responses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Responses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Content</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @responses.each do |response| %>
      <tr>
        <td><%= response.name %></td>
        <td><%= response.content %></td>
        <td><%= response.post_id %></td>
        <td><%= link_to 'Show', response %></td>
        <td><%= link_to 'Edit', edit_response_path(response) %></td>
        <td><%= link_to 'Destroy', response, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Response', new_response_path %>

app/views/responses/new.html.erb
<h1>New Response</h1>

<%= render 'form', response: @response %>

<%= link_to 'Back', responses_path %>

app/views/responses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @response.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @response.content %>
</p>

<p>
  <strong>Post:</strong>
  <%= @response.post_id %>
</p>

<%= link_to 'Edit', edit_response_path(@response) %> |
<%= link_to 'Back', responses_path %>

app/views/trips/_form.html.erb
<%= form_for(trip) do |f| %>
  <% if trip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
      <% trip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="text">
    <p>You can add a specific location here, if you know the coordinates.
      <br>Otherwise, just add a general address or location name to the Location field. examples: Astoria Oregon or Columbia River</p>
  </div>
  <div class="row">
    <div class="col-md-4">
      <div class="field">
        <%= f.label :Location %>
        <%= f.text_field :address %>
      </div>
    </div>

    <div class="col-md-2">
      <p>or add specific coordinates</p>
    </div>

    <div class="col-md-3">
      <div class="field">
        <%= f.label :latitude %>
        <%= f.text_field :latitude %>
      </div>

      <div class="field">
        <%= f.label :longitude %>
        <%= f.text_field :longitude %>
      </div>
    </div>

  </div>

  <p>Add a description of the day, tackle, weather, etc.</p>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :trip_date %>
    <%= f.date_select :trip_date %>
  </div>

  <div class="field">
    <%= f.hidden_field :user_id, :value => @user.id %>
  </div>





  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trips/edit.html.erb
<h1>Editing Trip</h1>

<%= render 'form', trip: @trip %>

<%= link_to 'Show', @trip %> |
<%= link_to 'Back', trips_path %>

app/views/trips/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trips</h1>

<table>
  <thead>
    <col width="300">
    <col width="300">

    <tr>
      <th>Address</th>
      <th>Trip date</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% current_user.trips.each do |trip| %>
      <tr>
        <td><%= link_to trip.address, trip %></td>
        <td><%= trip.trip_date %></td>


      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trip', new_trip_path %>

app/views/trips/new.html.erb
<h1>New Trip</h1>

<%= render 'form', trip: @trip %>

<%= link_to 'Back', trips_path %>

app/views/trips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Latitude:</strong>
  <%= @trip.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @trip.longitude %>
</p>

<p>
  <strong>Address:</strong>
  <%= @trip.address %>
</p>

<p>
  <strong>Description:</strong>
  <%= @trip.description %>
</p>

<p>
  <strong>Trip date:</strong>
  <%= @trip.trip_date %>
</p>

<%= link_to 'Edit', edit_trip_path(@trip) %> |
<%= link_to 'Destroy', trip_path, method: :delete, data: { confirm: 'Are you sure?' } %>
<br>
<br>
<%= link_to 'Back', root_path, data: { turbolinks: false } %>